default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_40436_development

<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_40436_test

<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
<<<<<<< Updated upstream
=======
  database: furima_40436_production
  username: furima_40436
  password: <%= ENV["FURIMA_40436_DATABASE_PASSWORD"] %>
>>>>>>> Stashed changes
